### ISSUE TITLE
As a user I can see a list of clients Høst has worked with

### ISSUE THREAD

**Issue by HellyStoyanova** [hostcreative/hostcreative#146]
Use as examples and inspiration
-  https://work.co/clients/
-https://docs.google.com/presentation/d/121aqi2JhNLLCiQGZ4I--gar47J7g9UgQ9DcMIPjN4ZE/edit#slide=id.g74efe9007c_1_0 (page 7)

**Comment by jayperryworks** [comment]
- [ ] WBG
- [ ] IFC
- [ ] UNOPS
- [ ] WFP
- [ ] UN Women
- [ ] UNICEF
- [ ] USAID
- [ ] EU
- [ ] GPE
- [ ] CGAP
- [ ] GFDRR
- [ ] CDC
- [ ] PPIAF
- [ ] GAIN
- [ ] GPOBA
